CREATE TABLE `pessoas` (
    id INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(192),
    `idade` INT,
    `cpf` VARCHAR(15),
    `rg` VARCHAR(15),
    `data_nasc` VARCHAR(10),
    `sexo` VARCHAR(11),
    `signo` VARCHAR(15),
    `mae` VARCHAR(192),
    `pai` VARCHAR(192),
    `email` VARCHAR(192),
    `senha` VARCHAR(64),
    `cep` VARCHAR(10),
    `endereco` VARCHAR(192),
    `numero` INT,
    `bairro` VARCHAR(192),
    `cidade` VARCHAR(192),
    `estado` VARCHAR(2),
    `telefone_fixo` VARCHAR(16),
    `celular` VARCHAR(16),
    `altura` VARCHAR(8),
    `peso` INT,
    `tipo_sanguineo` VARCHAR(6),
    `cor` VARCHAR(12),
    PRIMARY KEY(`id`)
) DEFAULT CHARACTER SET 'utf8';